import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "TPM ecommerce website",
  description: "Generated by create next app",
};
import NavbarSeller from "@/components/navbar_seller/navbar_seller";
import NavbarTopSeller from "@/components/navbar_top_seller/navbar_top_seller";
export default function RootLayout({ children, params }) {
  const { user_id_encode, seller_id_encode } = params;
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarSeller
          user_id_encode={user_id_encode}
          seller_id_encode={seller_id_encode}
        />
        <NavbarTopSeller />
        {children}
      </body>
    </html>
  );
}
